import Head from "next/head";
import { Fragment } from "react";
import Header from "../components/Header";
import Card from "../components/Card";
import foodie_1 from "../images/foodie_1.png";
import youboat_1 from "../images/youboat_1.png";
import spotter_1 from "../images/spotter_1_big.png";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Patrick | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Card
        title="Foodie"
        paragraph_one="A blog-like application for anyone to talk/share their experiences
         with food."
        paragraph_two="This was the second time using Chakra UI. It's brilliant documentation
         and usability makes creating reactive components simple and scalable.
        This was the first proper project using the Next.js framework. I found it's routing
         and server side rendering features extremely useful."
        image_one={foodie_1}
        languages={[
          "HTML5",
          "Javascript",
          "Next.js",
          "Chakra-UI",
          "Firebase",
          "Vercel",
        ]}
      />
      <Card
        title="YouBoat"
        paragraph_one="An Airbnb clone for renting boats."
        paragraph_two="First project my team and I worked on during our 9 week
         Ruby bootcamp. It was fantastic to be able to experience working collaboratively,
         from Figma to production."
        image_one={youboat_1}
        languages={[
          "HTML5",
          "CSS",
          "Ruby",
          "Ruby on Rails",
          "Cloudinary",
          "PostreSQL",
          "Heroku",
        ]}
      />
      <Card
        title="Currency Converter"
        paragraph_one="A simple currency converter built using React Native."
        paragraph_two="First project my team and I worked on during our 9 week
       Ruby bootcamp. It was fantastic to be able to experience working collaboratively,
       from Figma to production."
        image_one={youboat_1}
        languages={[
          "HTML5",
          "React",
          "Chakra-UI",
          "Currency Convert API",
          "Vercel",
        ]}
      />
      <Card
        title="Spotter"
        paragraph_one="Mobile app to find local skate areas."
        paragraph_two="The second project our team and I worked on during the bootcamp. We
        decided it would be far more suited on mobile, allowing users to create new spots
        they'd found, 'drop in' to spots they were at, alongside live feeds for which users
        were where."
        image_one={spotter_1}
        languages={[
          "HTML5",
          "React",
          "Chakra-UI",
          "Currency Convert API",
          "Vercel",
        ]}
      />
    </Fragment>
  );
}
