import Head from "next/head";
import { Fragment } from "react";

// portfolio components
import Header from "../components/header/Header";
import Card from "../components/card/Card";
import About from "../components/about/About";

// images
import profile from "../images/profile.jpg";
import foodie_1 from "../images/foodie_1.png";
import foodie_2 from "../images/foodie_2.png";
import youboat_1 from "../images/youboat_1.png";
import youboat_2 from "../images/youboat_2.png";
import spotter_1 from "../images/spotter_1_big.png";
import curreny_1 from "../images/currency_1.png";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Patrick | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header name="Patrick Hoveman" role="Junior Web Developer" />
      <About
        profile={profile}
        image_description="My profile Pic"
        description_1="Creative and driven full stack developer with diverse skills, who
         enjoys collaborative projects and working with others to make user experiences as
          smooth as possible."
        description_2="Long term goals are to become an effective and reliable software
        developer. In my spare time I like to play games, guitar, and cook."
      />
      <Card
        title="Foodie"
        paragraph_one="A blog-like application for anyone to talk/share their experiences
         with food."
        paragraph_two="This was the second time using Chakra UI. It's brilliant documentation
         and usability makes creating reactive components simple and scalable.
        This was the first proper project using the Next.js framework. I found it's routing
         and server side rendering features extremely useful."
        image_one={foodie_1}
        image_two={foodie_2}
        languages={[
          "HTML5",
          "Javascript",
          "Next.js",
          "Chakra-UI",
          "Firebase",
          "Vercel",
        ]}
      />
      <Card
        title="YouBoat"
        paragraph_one="An Airbnb clone for renting boats."
        paragraph_two="First project my team and I worked on during our 9 week
         Ruby bootcamp. It was fantastic to be able to experience working collaboratively,
         from Figma to production."
        image_one={youboat_1}
        image_two={youboat_2}
        languages={[
          "HTML5",
          "CSS",
          "Javascript",
          "Ruby",
          "Ruby on Rails",
          "Cloudinary",
          "PostreSQL",
          "Heroku",
        ]}
      />
      <Card
        title="Currency Converter"
        paragraph_one="A simple currency converter built using React Native."
        paragraph_two="First project my team and I worked on during our 9 week
       Ruby bootcamp. It was fantastic to be able to experience working collaboratively,
       from Figma to production."
        image_one={curreny_1}
        image_two={foodie_2}
        languages={[
          "HTML5",
          "React",
          "Chakra-UI",
          "Currency Convert API",
          "Vercel",
        ]}
      />
      <Card
        title="Spotter"
        paragraph_one="Mobile app to find local skate areas."
        paragraph_two="The second project our team and I worked on during the bootcamp. We
        decided it would be far more suited on mobile, allowing users to create new spots
        they'd found, 'drop in' to spots they were at, alongside live feeds for which users
        were where."
        image_one={spotter_1}
        image_two={foodie_2}
        languages={[
          "HTML5",
          "SCSS",
          "Javascript",
          "Ruby",
          "Ruby on Rails",
          "Mapbox API",
          "Cloudinary",
          "PostreSQL",
          "Heroku",
        ]}
      />
    </Fragment>
  );
}
